/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/area-discovery": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 投資エリア探索 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          prefecture: string;
          /** @description 予算 (円) */
          budget?: number;
          /** @description 目標利回り (例: 0.07) */
          yield?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.AreaDiscoveryResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/geocode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ジオコーディング */
    get: {
      parameters: {
        query: {
          /** @description 住所文字列 */
          address: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["api.GeocodeResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/hazard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ハザード情報 */
    get: {
      parameters: {
        query: {
          /** @description 緯度 (日本国内 20-46) */
          lat: number;
          /** @description 経度 (日本国内 122-154) */
          lng: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.UrbanRisk"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investment-score": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 投資適地スコア */
    get: {
      parameters: {
        query: {
          /** @description 緯度 (日本国内 20-46) */
          lat: number;
          /** @description 経度 (日本国内 122-154) */
          lng: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.InvestmentScoreResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investment-score-heatmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 投資スコアヒートマップ */
    get: {
      parameters: {
        query: {
          /** @description 南端緯度 */
          minLat: number;
          /** @description 北端緯度 */
          maxLat: number;
          /** @description 西端経度 */
          minLng: number;
          /** @description 東端経度 */
          maxLng: number;
          /** @description ズームレベル (11-15, デフォルト: 13) */
          z?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.HeatmapResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investment/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 投資分析 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description 投資分析リクエスト */
      requestBody: {
        content: {
          "application/json":
            | Record<string, never>
            | components["schemas"]["domain.InvestmentInput"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.InvestmentResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investment/rent-decline-hint": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 賃料下落率参考値 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 市区町村コード */
          municipality?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.RentDeclineHint"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investment/simulate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** モンテカルロシミュレーション */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description シミュレーションリクエスト */
      requestBody: {
        content: {
          "application/json":
            | Record<string, never>
            | components["schemas"]["domain.MonteCarloInput"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.MonteCarloResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/land-appraisals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 地価公示統計 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 公示年 (2022-2030) */
          year: number;
          /** @description 市区町村コード */
          city?: string;
          /** @description 用途区分 (00=住宅地, 05=商業地, 07=準工業地, 09=工業地) */
          division?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.AppraisalComparisonResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/land-prices/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 土地価格比較 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 開始年 (2005以降) */
          year: number;
          /** @description 開始四半期 (1-4) */
          quarter: number;
          /** @description 終了年 */
          to_year: number;
          /** @description 終了四半期 (1-4) */
          to_quarter: number;
          /** @description 検討物件価格 (円) */
          price: number;
          /** @description 市区町村コード */
          city?: string;
          /** @description 土地面積 (m²) */
          area_sqm?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.LandPriceComparison"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/land-prices/estimate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 理論価格推定 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 開始年 (2005以降) */
          year: number;
          /** @description 開始四半期 (1-4) */
          quarter: number;
          /** @description 終了年 */
          to_year: number;
          /** @description 終了四半期 (1-4) */
          to_quarter: number;
          /** @description 物件価格 (円) */
          price: number;
          /** @description 土地面積 (m²) */
          area_sqm: number;
          /** @description 市区町村コード */
          city?: string;
          /** @description 築年数 */
          building_age?: number;
          /** @description 最寄り駅徒歩分 */
          station_minutes?: number;
          /** @description 需要スコア (A-E) */
          ridership_score?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.TheoreticalPriceResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/land-prices/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 土地取引価格統計 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 開始年 (2005以降) */
          year: number;
          /** @description 開始四半期 (1-4) */
          quarter: number;
          /** @description 終了年 */
          to_year: number;
          /** @description 終了四半期 (1-4) */
          to_quarter: number;
          /** @description 市区町村コード */
          city?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.LandPriceStats"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/municipalities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 市区町村一覧 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["mlit.Municipality"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/population-forecast": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 将来推計人口 */
    get: {
      parameters: {
        query: {
          /** @description 緯度 */
          lat: number;
          /** @description 経度 */
          lng: number;
          /** @description ズームレベル (11-15, デフォルト: 14) */
          z?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.PopulationForecastResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/renovation/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** リフォームROI分析 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description リフォーム分析リクエスト */
      requestBody: {
        content: {
          "application/json":
            | Record<string, never>
            | components["schemas"]["domain.RenovationInput"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.RenovationResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/rent-stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 賃料統計 */
    get: {
      parameters: {
        query: {
          /** @description 都道府県コード (例: 13) */
          area: string;
          /** @description 市区町村コード */
          municipality?: string;
          /** @description 専有面積 (m²) */
          area_sqm?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.RentStatsResult"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/station-ridership": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 駅別乗降客数 */
    get: {
      parameters: {
        query: {
          /** @description 緯度 */
          lat: number;
          /** @description 経度 */
          lng: number;
          /** @description ズームレベル (11-15, デフォルト: 14) */
          z?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.StationRidershipResult"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Gateway */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/urban-risks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 都市計画リスク */
    get: {
      parameters: {
        query: {
          /** @description 緯度 (日本国内 20-46) */
          lat: number;
          /** @description 経度 (日本国内 122-154) */
          lng: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["domain.UrbanRisk"][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ヘルスチェック */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "api.GeocodeResult": {
      lat?: number;
      lng?: number;
      locationType?: string;
    };
    "domain.AcquisitionCostBreakdown": {
      /** @description 仲介手数料（税込） */
      brokerageFee?: number;
      /** @description 固定資産税日割り精算（買主負担分） */
      propertyTaxProration?: number;
      /** @description 不動産取得税（概算） */
      realEstateAcquisitionTax?: number;
      /** @description 登録免許税（所有権移転+抵当権設定） */
      registrationTax?: number;
      /** @description 印紙税（売買契約書） */
      stampDuty?: number;
      total?: number;
    };
    "domain.AppraisalComparisonResult": {
      /** @description 標準地点数 */
      appraisalCount?: number;
      /** @description 公示価格中央値（円/m²） */
      appraisalMedianPerSqm?: number;
      /** @description 平均変動率（小数） */
      appraisalTrend?: number;
      /** @description "上昇" / "安定" / "下落" */
      trendLabel?: string;
    };
    "domain.AreaDiscoveryItem": {
      /** @description 取引件数3件以上 */
      dataSufficient?: boolean;
      /** @description "上昇" | "安定" | "下落" | "不明" */
      landPriceTrend?: string;
      /** @description 坪単価中央値（円） */
      medianTsubo?: number;
      municipalityCode?: string;
      municipalityName?: string;
      /** @description 取引件数 */
      transactionCount?: number;
      /** @description "achievable" | "slightly-difficult" | "difficult" */
      yieldDifficulty?: string;
      /** @description 日本語ラベル */
      yieldDifficultyLabel?: string;
    };
    "domain.AreaDiscoveryResponse": {
      items?: components["schemas"]["domain.AreaDiscoveryItem"][];
      prefecture?: string;
    };
    /**
     * @description 建物構造
     * @enum {string}
     */
    "domain.BuildingType":
      | "木造"
      | "軽量鉄骨(4mm以下)"
      | "軽量鉄骨(3mm以下)"
      | "重量鉄骨"
      | "RC造"
      | "SRC造";
    "domain.CapexEvent": {
      /** @description 金額（円） */
      amount?: number;
      /** @description 何年目に発生（1〜保有年数） */
      year?: number;
    };
    "domain.ClassifiedRenovationItem": {
      cost?: number;
      expectedMonthlyRentIncrease?: number;
      isCapitalExpenditure?: boolean;
      isSelfWork?: boolean;
      name?: string;
      selfLaborHours?: number;
      virtualLaborCost?: number;
    };
    "domain.CriticalError": {
      code?: string;
      message?: string;
      status?: components["schemas"]["domain.CriticalErrorStatus"];
    };
    /** @enum {string} */
    "domain.CriticalErrorStatus": "REJECT" | "WARNING";
    "domain.HeatmapResponse": {
      tileCount?: number;
      tiles?: components["schemas"]["domain.HeatmapTile"][];
    };
    "domain.HeatmapTile": {
      centerLat?: number;
      centerLng?: number;
      grade?: string;
      totalScore?: number;
      x?: number;
      y?: number;
      z?: number;
    };
    "domain.HistogramBin": {
      count?: number;
      max?: number;
      min?: number;
    };
    "domain.InvestmentInput": {
      /** @description 現況空室率: 現時点の実際の空室状況（0の場合はVacancyRateと同一とみなす） */
      actualVacancyRate?: number;
      /** @description 入居者募集 AD（円/回）例: 家賃1ヶ月分 */
      adFee?: number;
      /** @description 年利 (例: 0.015) */
      annualLoanRate?: number;
      /** @description 年間固定資産税 (円)。ExpenseRate には含めないこと（二重計上になる） */
      annualPropertyTax?: number;
      /** @description 入退去コスト（全て optional。0 または未入力の場合はターンオーバーコスト = 0） */
      avgTenancyYears?: number;
      /** @description 築年数 (0=新築) */
      buildingAge?: number;
      /** @description 建築費 (円) */
      buildingCost?: number;
      buildingType?: components["schemas"]["domain.BuildingType"];
      /** @description 大規模修繕費スケジュール（最大5件） */
      capexSchedule?: components["schemas"]["domain.CapexEvent"][];
      /** @description 減価償却方式: "straight-line"（定額法）| "declining-balance"（定率法） */
      depreciationMethod?: string;
      /** @description 割引率: NPV/IRR計算用 (例: 0.05 = 5%) */
      discountRate?: number;
      /** @description 複数保有年数の出口比較: 空の場合は [5, 10, 15, 20] をデフォルトとして使用 */
      exitYears?: number[];
      /** @description 出口戦略: 売却時目標利回り（実質ベース。NOI / 売却価格） */
      exitYieldTarget?: number;
      /** @description 経費インフレ率/年 (例: 0.01 = 1%) */
      expenseInflationRate?: number;
      /**
       * @description 運営経費率 (管理費・修繕・保険等。固定資産税・ローン利息は含まない)
       *     固定資産税は AnnualPropertyTax で別途指定する
       */
      expenseRate?: number;
      /** @description 出口戦略: 売却年数 (例: 10) */
      holdingYears?: number;
      /** @description 所得税率 (例: 0.33。給与との合算後実効税率) */
      incomeTaxRate?: number;
      /** @description 保険料率 (例: 0.003 = 0.3%) */
      insuranceFeeRate?: number;
      /** @description 土地面積 (m²) */
      landArea?: number;
      /** @description 土地取得費 (円) */
      landPrice?: number;
      /** @description ローン金額 (円) */
      loanAmount?: number;
      /** @description 融資諸費用率（保証料・登記費用等の合算）。LoanAmount × LoanFeeRate を取得費に加算。 */
      loanFeeRate?: number;
      /**
       * @description 返済方式: "equal-payment"（元利均等）| "equal-principal"（元金均等）
       *     省略時は Defaults() で "equal-payment" にセットされる。
       */
      loanMethod?: string;
      /** @description 金利上昇分 (例: +0.015) */
      loanRateDelta?: number;
      /** @description ローン期間 (年) */
      loanYears?: number;
      /** @description 詳細経費内訳（全てoptional・後方互換）。合計 > 0 の場合は ExpenseRate より優先される。 */
      managementFeeRate?: number;
      /** @description 諸経費率 (例: 0.07) */
      miscExpenseRate?: number;
      /** @description 想定月額賃料 (円) */
      monthlyRent?: number;
      /** @description その他経費率 (例: 0.005 = 0.5%) */
      otherExpenseRate?: number;
      /** @description 物件価格下落率: 売却価格に毎年この割合の累乗で下落を反映 (例: 0.02 = 年2%下落) */
      priceDeclineRate?: number;
      /**
       * @description 変動金利スケジュール: 指定年以降に適用する金利ステップ（空=固定金利）
       *     LoanRateDelta はスケジュール後の金利にも加算される。
       */
      rateAdjustmentSchedule?: components["schemas"]["domain.RateAdjustment"][];
      /** @description 賃料下落率: 毎年この割合だけ実効賃料が低下する（例: 0.01 = 年1%下落） */
      rentDeclineRate?: number;
      /** @description フリーレント（ヶ月）例: 0.5 */
      rentFreePeriod?: number;
      /**
       * @description 賃料上昇シナリオ（新築・リノベ向け）
       *     RentGrowthYears 年間は RentGrowthRate で上昇し、その後 RentDeclineRate で下落する。
       *     どちらかが 0 の場合は従来の RentDeclineRate のみが適用される。
       */
      rentGrowthRate?: number;
      /** @description 上昇が続く年数 */
      rentGrowthYears?: number;
      /** @description 修繕積立費率 (例: 0.01 = 1%) */
      repairReserveRate?: number;
      /** @description 原状回復費（円/回）例: 150000 */
      restorationCost?: number;
      /** @description 空室率 (例: 0.05) */
      vacancyRate?: number;
      /** @description ストレステスト用オフセット */
      vacancyRateDelta?: number;
      /** @description 目標表面利回り（例: 0.08 = 8%）。0 の場合は Defaults() で 0.08 にセットされる。 */
      yieldTarget?: number;
    };
    "domain.InvestmentResult": {
      acquisitionCosts?: components["schemas"]["domain.AcquisitionCostBreakdown"];
      /** @description Gemini 生成の投資サマリー（空文字 = 未生成） */
      aiSummary?: string;
      criticalErrors?: components["schemas"]["domain.CriticalError"][];
      /** @description -1 = デッドクロスなし */
      deadCrossYear?: number;
      /** @description 1年目の借入金償還余裕率（NOI/年間返済額） */
      dscr?: number;
      /** @description 譲渡所得 */
      exitCapitalGain?: number;
      /** @description 売却手取り（税・残債控除後） */
      exitNetProceeds?: number;
      /** @description 売却価格（NOI/目標利回り） */
      exitSalePrice?: number;
      /** @description 最終手残り（売却手取り+累積CF） */
      exitTotalEquity?: number;
      /** @description 譲渡所得税 */
      exitTransferTax?: number;
      /** @description 表面利回り（満室想定年収/総投資額） */
      grossYield?: number;
      /** @description 内部収益率（収束しない場合は null） */
      irr?: number;
      isAboveYieldTarget?: boolean;
      /** @description LTV感度分析（50%〜90%） */
      ltvSensitivity?: components["schemas"]["domain.LTVSensitivityRow"][];
      miscExpenses?: number;
      /** @description 複数保有年数の出口比較 */
      multiExitComparison?: components["schemas"]["domain.MultiExitRow"][];
      /** @description 実質利回り（実効収入-経費)/総投資額） */
      netYield?: number;
      /** @description 正味現在価値 */
      npv?: number;
      /** @description 目標利回り達成に必要な改善額（土地・建築費いずれか一方を削減する額） */
      requiredCostReduction?: number;
      /** @description または必要月額賃料 */
      requiredMonthlyRent?: number;
      stressScenarios?: components["schemas"]["domain.StressScenarioResult"][];
      /** @description 保有期間の総支払利息 */
      totalInterest?: number;
      /** @description 総投資額（土地+建物+諸経費） */
      totalInvestment?: number;
      yearlyResults?: components["schemas"]["domain.YearlyResult"][];
      yieldScenarios?: components["schemas"]["domain.YieldScenarios"];
      /** @description 目標表面利回り（例: 0.08） */
      yieldTarget?: number;
    };
    "domain.InvestmentScoreResult": {
      breakdown?: components["schemas"]["domain.ScoreBreakdown"];
      /** @description 優良/良好/普通/注意/要注意 */
      grade?: string;
      totalScore?: number;
    };
    "domain.LTVSensitivityRow": {
      /** @description 年間キャッシュフロー（円） */
      annualCF?: number;
      /** @description CF利回り（AnnualCF / 総投資額） */
      cfYield?: number;
      /** @description 借入金償還余裕率 */
      dscr?: number;
      /** @description 自己資金（円） */
      equity?: number;
      /** @description 借入額（円） */
      loanAmount?: number;
      /** @description 借入比率（例: 0.70） */
      ltv?: number;
    };
    "domain.LandPriceComparison": {
      /** @description "割安" / "相場" / "割高" */
      assessment?: string;
      diffFromAverage?: number;
      diffFromMedian?: number;
      inputArea?: number;
      inputLandPrice?: number;
      inputPricePerTsubo?: number;
      stats?: components["schemas"]["domain.LandPriceStats"];
    };
    "domain.LandPriceStats": {
      averageTsubo?: number;
      count?: number;
      /** @description 件数 < 10 件時 true */
      lowDataWarning?: boolean;
      maxTsubo?: number;
      medianTsubo?: number;
      minTsubo?: number;
      transactions?: components["schemas"]["domain.LandTransaction"][];
      /** @description 都市計画リスク一覧 */
      urbanRisks?: components["schemas"]["domain.UrbanRisk"][];
      warningMessage?: string;
      zoning?: components["schemas"]["domain.ZoningSummary"];
    };
    "domain.LandTransaction": {
      area?: number;
      buildingCoverage?: string;
      /** @description 建築年（西暦） */
      buildingYear?: number;
      cityPlanning?: string;
      district?: string;
      floorAreaRatio?: string;
      period?: string;
      pricePerSqm?: number;
      pricePerTsubo?: number;
      /** @description 最寄り駅徒歩分 */
      stationMinutes?: number;
      tradePrice?: number;
    };
    "domain.MonteCarloInput": {
      base?: components["schemas"]["domain.InvestmentInput"];
      /** @description 金利の標準偏差 (デフォルト 0.005) */
      loanRateSigma?: number;
      /** @description 試行回数 (デフォルト 1000、最大 10000) */
      simulations?: number;
      /** @description 空室率の標準偏差 (デフォルト 0.05) */
      vacancyRateSigma?: number;
    };
    "domain.MonteCarloResult": {
      /** @description デッドクロス発生率 (0〜1) */
      deadCrossRate?: number;
      equityHistogram?: components["schemas"]["domain.HistogramBin"][];
      equityPercentiles?: components["schemas"]["domain.Percentiles"];
      irrHistogram?: components["schemas"]["domain.HistogramBin"][];
      irrPercentiles?: components["schemas"]["domain.Percentiles"];
      simulationCount?: number;
      /** @description IRR > 0 の割合 */
      successRate?: number;
    };
    "domain.MultiExitRow": {
      cumulativeCf?: number;
      exitEquity?: number;
      irr?: number;
      isShortTermWarn?: boolean;
      remainingLoan?: number;
      salePrice?: number;
      transferTax?: number;
      transferTaxRate?: number;
      year?: number;
    };
    "domain.Percentiles": {
      p10?: number;
      p25?: number;
      p50?: number;
      p75?: number;
      p90?: number;
    };
    "domain.PopulationForecastResult": {
      /** @description 30年後変化率 (例: -0.32) */
      changeRate30yr?: number;
      snapshots?: components["schemas"]["domain.PopulationSnapshot"][];
      trend?: components["schemas"]["domain.PopulationTrend"];
      /** @description 推定空室率増加幅 */
      vacancyRateDelta?: number;
    };
    "domain.PopulationSnapshot": {
      pop?: number;
      year?: number;
    };
    /** @enum {string} */
    "domain.PopulationTrend": "増加" | "現状維持" | "緩やかな減少" | "急激な減少";
    "domain.RadarPoint": {
      category?: string;
      score?: number;
    };
    "domain.RateAdjustment": {
      /** @description AfterYear: この年（1始まり）以降に Rate を適用（例: 6 = 6年目から） */
      afterYear?: number;
      /** @description Rate: 絶対値の年利（例: 0.02 = 2%） */
      rate?: number;
    };
    "domain.RenovationInput": {
      annualBaseRent?: number;
      annualExpenses?: number;
      effectiveTaxRate?: number;
      items?: components["schemas"]["domain.RenovationItem"][];
      propertyPrice?: number;
      selfLaborRatePerHour?: number;
    };
    "domain.RenovationItem": {
      cost?: number;
      expectedMonthlyRentIncrease?: number;
      isSelfWork?: boolean;
      name?: string;
      selfLaborHours?: number;
    };
    "domain.RenovationResult": {
      actualYield?: number;
      annualRentIncrease?: number;
      capitalExpenditures?: number;
      classifiedItems?: components["schemas"]["domain.ClassifiedRenovationItem"][];
      /** @description 家賃アップがある場合のみ true */
      isRecoverable?: boolean;
      recoveryYears?: number;
      repairExpenses?: number;
      taxSavings?: number;
      totalRenovationCost?: number;
      virtualLaborCost?: number;
    };
    "domain.RentDeclineHint": {
      /** @description "land_appraisal" | "fallback" */
      basis?: string;
      /** @description 使用した地価公示データ件数 */
      dataPointCount?: number;
      fallbackUsed?: boolean;
      /** @description 参考下落率（小数: 0.008 = 0.8%/年） */
      hintRate?: number;
      note?: string;
    };
    "domain.RentStatsResult": {
      /** @description 月額賃料 平均値（円） */
      average?: number;
      /** @description サンプル数 */
      count?: number;
      /** @description 月額賃料 中央値（円） */
      median?: number;
    };
    /**
     * @description 需要スコア (有効時のみ)
     * @enum {string}
     */
    "domain.RidershipDemandScore": "A" | "B" | "C" | "D" | "E";
    "domain.ScoreBreakdown": {
      disasterHistory?: components["schemas"]["domain.ScoreItem"];
      embankment?: components["schemas"]["domain.ScoreItem"];
      hazardRisk?: components["schemas"]["domain.ScoreItem"];
      landPriceTrend?: components["schemas"]["domain.ScoreItem"];
      liquefactionRisk?: components["schemas"]["domain.ScoreItem"];
      locationOptimization?: components["schemas"]["domain.ScoreItem"];
      population?: components["schemas"]["domain.ScoreItem"];
      radarData?: components["schemas"]["domain.RadarPoint"][];
      ridership?: components["schemas"]["domain.ScoreItem"];
      urbanArea?: components["schemas"]["domain.ScoreItem"];
    };
    "domain.ScoreItem": {
      description?: string;
      label?: string;
      score?: number;
    };
    "domain.StationRidershipResult": {
      /** @description 理論価格補正係数 */
      correction?: number;
      demandScore?: components["schemas"]["domain.RidershipDemandScore"];
      lineName?: string;
      /** @description 乗降客数/日 */
      passengers?: number;
      stationName?: string;
    };
    "domain.StressScenarioResult": {
      /** @description 累積税引後CFが初めて正転する年（-1=なし） */
      breakEvenYear?: number;
      dscr?: number;
      interestRateDelta?: number;
      /** @description DSCR >= 1.0 && BreakEvenYear <= HoldingYears（UIバッジは1.2閾値、フラグ定義は変更しない） */
      isSafe?: boolean;
      label?: string;
      totalCashFlow?: number;
      vacancyRateDelta?: number;
    };
    "domain.TheoreticalPriceResult": {
      /** @description 築年数補正 (-0.3〜0.3) */
      ageCorrection?: number;
      /** @description 乖離率 % (正=割高, 負=割安) */
      deviationPct?: number;
      /** @description 乗降客数補正が有効か */
      hasRidershipData?: boolean;
      /** @description 駅距離補正が有効か */
      hasStationData?: boolean;
      /** @description 築年数サンプル不足 */
      isLowDataWarning?: boolean;
      /** @description 取引事例中央値築年数 */
      medianBuildingAge?: number;
      /** @description 取引事例中央値駅距離(分) */
      medianStationMinutes?: number;
      /** @description 乗降客数補正 (-0.15〜0.15) */
      ridershipCorrection?: number;
      ridershipScore?: components["schemas"]["domain.RidershipDemandScore"];
      /** @description 駅距離補正 (-0.2〜0.2) */
      stationCorrection?: number;
      /** @description 理論価格 (円) */
      theoreticalPriceJPY?: number;
    };
    "domain.UrbanRisk": {
      /** @description リスクコード（例: URBANIZATION_CONTROL） */
      code?: string;
      /** @description 詳細説明 */
      description?: string;
      level?: components["schemas"]["domain.UrbanRiskLevel"];
      /** @description 短いタイトル */
      title?: string;
    };
    /**
     * @description ERROR / WARNING / INFO
     * @enum {string}
     */
    "domain.UrbanRiskLevel": "ERROR" | "WARNING" | "INFO";
    "domain.YearlyResult": {
      afterTaxCashFlow?: number;
      annualDepreciation?: number;
      annualExpenses?: number;
      annualInterest?: number;
      annualLoanPayment?: number;
      annualPrincipal?: number;
      /** @description 実効賃料収入（空室控除後） */
      annualRent?: number;
      /** @description 大規模修繕費（当年発生額） */
      capexAmount?: number;
      cashFlow?: number;
      cumulativeCashFlow?: number;
      /** @description その年の適用金利（年利） */
      effectiveRate?: number;
      incomeTax?: number;
      /** @description デッドクロス初年度 */
      isDeadCrossYear?: boolean;
      /** @description デッドクロス継続中 */
      isInDeadCrossZone?: boolean;
      remainingLoanBalance?: number;
      taxableIncome?: number;
      year?: number;
    };
    /** @description 楽観: 空室率 × 0.5 */
    "domain.YieldScenario": {
      /** @description 年間実効賃料収入（空室控除後） */
      annualRent?: number;
      /** @description 表面利回り（満室想定年収/総投資額） */
      grossYield?: number;
    };
    "domain.YieldScenarios": {
      optimistic?: components["schemas"]["domain.YieldScenario"];
      pessimistic?: components["schemas"]["domain.YieldScenario"];
      standard?: components["schemas"]["domain.YieldScenario"];
    };
    /** @description 取引データから抽出した用途地域情報 */
    "domain.ZoningSummary": {
      /** @description 最頻の建ぺい率（例: 60%） */
      buildingCoverage?: string;
      /** @description 最頻の都市計画区域（例: 第一種住居地域） */
      cityPlanning?: string;
      /** @description 最頻の容積率（例: 200%） */
      floorAreaRatio?: string;
    };
    "mlit.Municipality": {
      /** @description 市区町村コード (例: "13101") */
      id?: string;
      /** @description 市区町村名 (例: "千代田区") */
      name?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
